### PR TITLE
Clarification on linearity/gaussian assumption?

### PR DESCRIPTION
**Pull request by MikeInnes**
This is a great idea, and I enjoyed the article that came with it.

The model's predictions are a bit surprising, though, given that estimated cases tail sharply off, despite official counts rising ever more steeply.

This happens because of the assumption that seroprevalance is proportional to the log of case and death counts. In other words, new cases are heavily discounted when counts are high, to the extent that eventually a new official case counts for less than one estimated case. Some discount might be justified by increasingly thorough testing (though this wouldn't apply to excess mortality), but this amount seems unrealistic, and doesn't appear to be justified by the sero dataset.

Since the data are binomial distributed, I tried tweaking this code to do a binomial regression instead. This generates quite different, and to me more plausible, results (and appears to learn its own discount from the sero data). Those are on the left below, with the originals for comparison on the right.

g2474

It would be great to get your thoughts on this, and to better understand why unusual statistical assumptions were chosen for this model.

### CODE REVIEW

**Comment by sondreus** [comment]
Thank you Mike, I'm glad you liked the article and approach.

The model becomes more uncertain over time, as our confidence interval shows and we write in the code. As we get closer to the present day the number of tests done per day are increasing in most countries, while the number of sero-surveys with published results is decreasing (though many are underway). This makes for a sparser "feature space", especially as countries continue to ramp up testing. 

As you note, the model assumes that seroprevalence is proportional to the log of case and death counts and their interaction, with all three scaled by the log of average incomes (to account for testing capacity). For certain combinations of the data, this might indeed mean that an increase in estimated seroprevalence can be lower than that implied by new diagnosed cases for that day. This is of course not impossible (due to e.g. lag between infection and testing, or decline in people with measurable antibodies, as suggested by some of the seroprevalence data), though perhaps a bit strange. One interpretation is that the model previously thought the country was underestimating to a very high extent, for instance because deaths were very high relative to cases. As cases per death increases, the model comes to believe that measured cases better reflect underlying seropositivity, and thus downward adjusts its estimates for the latter. Overall, this is based on the assumption that as diagnosed cases and deaths increase, they have come to better reflect the underlying seropositivity, which seems borne out by the data. Overall, our model explained about 70 percent of observed variation in seropositivity, which is pretty good considering the enormous variation in areas with seropositivity data (from a nation-wide survey of India to small rural administrative units of Sweden).

With regards to modelling approaches, we tried several. In addition to the suggested binomial regression, we also tried more complex non-parametric methods such as random forests (which avoids the log vs non-log question), and beta-regression (which has more distributional assumptions, like logistic regression). The results were similar (lower overall count for random forests, higher for beta regression). We preferred a linear model because such models tend to more robust. Both beta-regression (and logistic regression, for that matter), and boot-strap based methods such as random forests may struggle when sample sizes are on the small side, which is especially problematic here as we seek to extrapolate to the extent one has to to produce global estimates. As a bonus, linear model have the advantage of being more interpretable, which is a useful quality here. In addition to thinking through these issues we validated our model by looking at the countries for which we have seropositivity estimates at the national level at certain points, where they synced up quite well. We also double-checked influential observations (a national survey of Afghanistan had particularly high leverage, so we reached out to the WHO to confirm the result). 

With regards to the alternative you propose specifically, your estimates of the global case counts are probably much too high. At the time we estimated these models (mid September), the WHO said that based on their ongoing work and the surveys it had access to (many of them not yet released), they estimated that less than 10% of the world had been infected at any point (that would be 780m, they would not give a lower bound). We estimated 6.4% to 9.3%, while your suggestion would put it at over 20%. In early October, they put the number at roughly 10%, or a bit more than 20x confirmed cases (pretty much the exact multiplier this model estimated 3 weeks prior, with the extra percentage points being made up by new cases in the interim).

All that said, it may of course be that our estimates later months are too low (as I stress, these are more uncertain), and perhaps serosurveys now being released from these dates will show it. New surveys and covariates (e.g. on testing) also opens up to more flexible modelling approaches, which we might explore in future work. 

Hope this is useful.

**Comment by MikeInnes** [comment]
Thanks a lot for the detailed and interesting response, Sondre.

> The model becomes more uncertain over time ...

Although the plotted intervals do increase over time, this surely only reflects the number of cases itself increasing, right? The uncertainty in the seroprevalence estimates is roughly constant, ie if I plot `pred_ir_high - pred_ir_low` over time there's no clear trend. It would be very surprising if there was, given that the model has no notion of time. (This is not to disagree that uncertainty should increase with time in principle, for the reasons you mention; just that this model can't represent those reasons.)

> Overall, our model explained about 70 percent of observed variation in seropositivity

Do I understand correctly that you're talking about R^2, as in:

```R
pred <- predict(lm_model)
pred[pred < 0] <- 0
1 - mean((sero$sero_ir - pred)^2) / var(sero$sero_ir)
```

I'm getting about 38% for the linear model and 54% for the binomial here (I might be missing something, this is not how I'd usually compare models but I want to do it like-for-like). Would appreciate pointers to reproduce the 70% figure.

> your estimates of the global case counts are probably much too high.

Yeah, I agree with that. I suspect there may be some bias in the dataset worth correcting for, but plan to investigate further. Still, accuracy in predicting seroprevalence seems like the thing to aim for here, and the log assumption feels uncomfortably like begging the question unless it improves that.

(Incidentally, both models are disturbingly sensitive to the `death_r+10^-5` fudge parameter; using your value brings my estimate down towards 1B.)

**Comment by sondreus** [comment]
Great, glad it could help. Yes - there is no explicit time trend, but using the total cases and deaths means that it is present implicitly and scaled by the diagnosed outbreak in the relevant country, which to me makes more sense. For the r-squared, type "summary(lm_model)", it should give "Adjusted R-squared:  0.7156". 

I am not entirely sure what you mean by "begging the question", or bias in the dataset. If you have found any inaccuracies in the dataset, do let me know so I can correct it. Thanks!

**Comment by MikeInnes** [comment]
By bias in the data set, I don't mean inaccuracies, but simply that the data might not be representative of all the countries we're extrapolating to. For example, there are a lot of rich European countries and only one African one (the model might over-extrapolate the effect of GDP). If serosurveys are more likely to be carried out in known hotspots with higher seroprevalence (eg London, New York), that would also add a systematic error to estimates. I'm sure you've thought about these kinds of things, so we may just be using different terms and talking at cross purposes.

**Comment by sondreus** [comment]
I see - yes, that was a major concern. I did spend many hours tracking down surveys in developing countries, but they are few and far between. Hopefully more are done soon!

**Pull request closed without merging**
